import type { ComponentStory, ComponentMeta } from '@storybook/react';
import { RecentlyPlayed } from './RecentlyPlayed';
import { createMemoryRouter, RouterProvider } from 'react-router-dom';

const Story: ComponentMeta<typeof RecentlyPlayed> = {
  component: RecentlyPlayed,
  title: 'home/feature/RecentlyPlayed',
};
export default Story;

const Template: ComponentStory<typeof RecentlyPlayed> = () => {
  const router = createMemoryRouter([
    {
      element: <RecentlyPlayed />,
      path: '/',
      loader: () => ({
        items: [
          {
            track: {
              album: {
                album_type: 'album',
                artists: [
                  {
                    external_urls: {
                      spotify:
                        'https://open.spotify.com/artist/3D5DKmCiZ3VQRu68k87E3Q',
                    },
                    href: 'https://api.spotify.com/v1/artists/3D5DKmCiZ3VQRu68k87E3Q',
                    id: '3D5DKmCiZ3VQRu68k87E3Q',
                    name: 'Lala Karmela',
                    type: 'artist',
                    uri: 'spotify:artist:3D5DKmCiZ3VQRu68k87E3Q',
                  },
                ],
                available_markets: [
                  'AD',
                  'AE',
                  'AG',
                  'AL',
                  'AM',
                  'AO',
                  'AR',
                  'AT',
                  'AU',
                  'AZ',
                  'BA',
                  'BB',
                  'BD',
                  'BE',
                  'BF',
                  'BG',
                  'BH',
                  'BI',
                  'BJ',
                  'BN',
                  'BO',
                  'BR',
                  'BS',
                  'BT',
                  'BW',
                  'BY',
                  'BZ',
                  'CA',
                  'CD',
                  'CG',
                  'CH',
                  'CI',
                  'CL',
                  'CM',
                  'CO',
                  'CR',
                  'CV',
                  'CW',
                  'CY',
                  'CZ',
                  'DE',
                  'DJ',
                  'DK',
                  'DM',
                  'DO',
                  'DZ',
                  'EC',
                  'EE',
                  'EG',
                  'ES',
                  'ET',
                  'FI',
                  'FJ',
                  'FM',
                  'FR',
                  'GA',
                  'GB',
                  'GD',
                  'GE',
                  'GH',
                  'GM',
                  'GN',
                  'GQ',
                  'GR',
                  'GT',
                  'GW',
                  'GY',
                  'HK',
                  'HN',
                  'HR',
                  'HT',
                  'HU',
                  'ID',
                  'IE',
                  'IL',
                  'IN',
                  'IQ',
                  'IS',
                  'IT',
                  'JM',
                  'JO',
                  'JP',
                  'KE',
                  'KG',
                  'KH',
                  'KI',
                  'KM',
                  'KN',
                  'KR',
                  'KW',
                  'KZ',
                  'LA',
                  'LB',
                  'LC',
                  'LI',
                  'LK',
                  'LR',
                  'LS',
                  'LT',
                  'LU',
                  'LV',
                  'LY',
                  'MA',
                  'MC',
                  'MD',
                  'ME',
                  'MG',
                  'MH',
                  'MK',
                  'ML',
                  'MN',
                  'MO',
                  'MR',
                  'MT',
                  'MU',
                  'MV',
                  'MW',
                  'MX',
                  'MY',
                  'MZ',
                  'NA',
                  'NE',
                  'NG',
                  'NI',
                  'NL',
                  'NO',
                  'NP',
                  'NR',
                  'NZ',
                  'OM',
                  'PA',
                  'PE',
                  'PG',
                  'PH',
                  'PK',
                  'PL',
                  'PS',
                  'PT',
                  'PW',
                  'PY',
                  'QA',
                  'RO',
                  'RS',
                  'RW',
                  'SA',
                  'SB',
                  'SC',
                  'SE',
                  'SG',
                  'SI',
                  'SK',
                  'SL',
                  'SM',
                  'SN',
                  'SR',
                  'ST',
                  'SV',
                  'SZ',
                  'TD',
                  'TG',
                  'TH',
                  'TJ',
                  'TL',
                  'TN',
                  'TO',
                  'TR',
                  'TT',
                  'TV',
                  'TW',
                  'TZ',
                  'UA',
                  'UG',
                  'US',
                  'UY',
                  'UZ',
                  'VC',
                  'VE',
                  'VN',
                  'VU',
                  'WS',
                  'XK',
                  'ZA',
                  'ZM',
                  'ZW',
                ],
                external_urls: {
                  spotify:
                    'https://open.spotify.com/album/6XqNorK0XDn5kPMnqLuBxk',
                },
                href: 'https://api.spotify.com/v1/albums/6XqNorK0XDn5kPMnqLuBxk',
                id: '6XqNorK0XDn5kPMnqLuBxk',
                images: [
                  {
                    height: 640,
                    url: 'https://i.scdn.co/image/ab67616d0000b273d462cb84c9899a5a132101a1',
                    width: 640,
                  },
                  {
                    height: 300,
                    url: 'https://i.scdn.co/image/ab67616d00001e02d462cb84c9899a5a132101a1',
                    width: 300,
                  },
                  {
                    height: 64,
                    url: 'https://i.scdn.co/image/ab67616d00004851d462cb84c9899a5a132101a1',
                    width: 64,
                  },
                ],
                name: 'Kamu, Aku, Cinta',
                release_date: '2011-02-21',
                release_date_precision: 'day',
                total_tracks: 12,
                type: 'album',
                uri: 'spotify:album:6XqNorK0XDn5kPMnqLuBxk',
              },
              artists: [
                {
                  external_urls: {
                    spotify:
                      'https://open.spotify.com/artist/00o36BiAS5VuyfvzNtd3Ig',
                  },
                  href: 'https://api.spotify.com/v1/artists/00o36BiAS5VuyfvzNtd3Ig',
                  id: '00o36BiAS5VuyfvzNtd3Ig',
                  name: 'Ello',
                  type: 'artist',
                  uri: 'spotify:artist:00o36BiAS5VuyfvzNtd3Ig',
                },
                {
                  external_urls: {
                    spotify:
                      'https://open.spotify.com/artist/0z62BK7Dlf4pui37XDARci',
                  },
                  href: 'https://api.spotify.com/v1/artists/0z62BK7Dlf4pui37XDARci',
                  id: '0z62BK7Dlf4pui37XDARci',
                  name: 'Barry',
                  type: 'artist',
                  uri: 'spotify:artist:0z62BK7Dlf4pui37XDARci',
                },
                {
                  external_urls: {
                    spotify:
                      'https://open.spotify.com/artist/5GlpZ7HnQxaNiHxPeE2bR3',
                  },
                  href: 'https://api.spotify.com/v1/artists/5GlpZ7HnQxaNiHxPeE2bR3',
                  id: '5GlpZ7HnQxaNiHxPeE2bR3',
                  name: 'Ipank',
                  type: 'artist',
                  uri: 'spotify:artist:5GlpZ7HnQxaNiHxPeE2bR3',
                },
                {
                  external_urls: {
                    spotify:
                      'https://open.spotify.com/artist/3D5DKmCiZ3VQRu68k87E3Q',
                  },
                  href: 'https://api.spotify.com/v1/artists/3D5DKmCiZ3VQRu68k87E3Q',
                  id: '3D5DKmCiZ3VQRu68k87E3Q',
                  name: 'Lala Karmela',
                  type: 'artist',
                  uri: 'spotify:artist:3D5DKmCiZ3VQRu68k87E3Q',
                },
              ],
              available_markets: [
                'AD',
                'AE',
                'AG',
                'AL',
                'AM',
                'AO',
                'AR',
                'AT',
                'AU',
                'AZ',
                'BA',
                'BB',
                'BD',
                'BE',
                'BF',
                'BG',
                'BH',
                'BI',
                'BJ',
                'BN',
                'BO',
                'BR',
                'BS',
                'BT',
                'BW',
                'BY',
                'BZ',
                'CA',
                'CD',
                'CG',
                'CH',
                'CI',
                'CL',
                'CM',
                'CO',
                'CR',
                'CV',
                'CW',
                'CY',
                'CZ',
                'DE',
                'DJ',
                'DK',
                'DM',
                'DO',
                'DZ',
                'EC',
                'EE',
                'EG',
                'ES',
                'ET',
                'FI',
                'FJ',
                'FM',
                'FR',
                'GA',
                'GB',
                'GD',
                'GE',
                'GH',
                'GM',
                'GN',
                'GQ',
                'GR',
                'GT',
                'GW',
                'GY',
                'HK',
                'HN',
                'HR',
                'HT',
                'HU',
                'ID',
                'IE',
                'IL',
                'IN',
                'IQ',
                'IS',
                'IT',
                'JM',
                'JO',
                'JP',
                'KE',
                'KG',
                'KH',
                'KI',
                'KM',
                'KN',
                'KR',
                'KW',
                'KZ',
                'LA',
                'LB',
                'LC',
                'LI',
                'LK',
                'LR',
                'LS',
                'LT',
                'LU',
                'LV',
                'LY',
                'MA',
                'MC',
                'MD',
                'ME',
                'MG',
                'MH',
                'MK',
                'ML',
                'MN',
                'MO',
                'MR',
                'MT',
                'MU',
                'MV',
                'MW',
                'MX',
                'MY',
                'MZ',
                'NA',
                'NE',
                'NG',
                'NI',
                'NL',
                'NO',
                'NP',
                'NR',
                'NZ',
                'OM',
                'PA',
                'PE',
                'PG',
                'PH',
                'PK',
                'PL',
                'PS',
                'PT',
                'PW',
                'PY',
                'QA',
                'RO',
                'RS',
                'RW',
                'SA',
                'SB',
                'SC',
                'SE',
                'SG',
                'SI',
                'SK',
                'SL',
                'SM',
                'SN',
                'SR',
                'ST',
                'SV',
                'SZ',
                'TD',
                'TG',
                'TH',
                'TJ',
                'TL',
                'TN',
                'TO',
                'TR',
                'TT',
                'TV',
                'TW',
                'TZ',
                'UA',
                'UG',
                'US',
                'UY',
                'UZ',
                'VC',
                'VE',
                'VN',
                'VU',
                'WS',
                'XK',
                'ZA',
                'ZM',
                'ZW',
              ],
              disc_number: 1,
              duration_ms: 232746,
              explicit: false,
              external_ids: {
                isrc: 'IDAC50900194',
              },
              external_urls: {
                spotify:
                  'https://open.spotify.com/track/6lZKJkfn0eVCXvbh1jsO8a',
              },
              href: 'https://api.spotify.com/v1/tracks/6lZKJkfn0eVCXvbh1jsO8a',
              id: '6lZKJkfn0eVCXvbh1jsO8a',
              is_local: false,
              name: 'Buka Semangat Baru',
              popularity: 48,
              preview_url:
                'https://p.scdn.co/mp3-preview/5a7972daabee88ee827d7411eaf4f5e268649fe0?cid=b8b35b1f317e44f5a24f7617fe6eb34d',
              track_number: 7,
              type: 'track',
              uri: 'spotify:track:6lZKJkfn0eVCXvbh1jsO8a',
            },
            played_at: '2023-01-16T11:42:49.111Z',
            context: null,
          },
        ],
      }),
    },
  ]);

  return <RouterProvider router={router} />;
};

export const Primary = Template.bind({});
Primary.args = {};
