import { RecentlyPlayedList } from '@react-spotify/home-components';

const mockItems = {
  items: [
    {
      track: {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi',
              },
              href: 'https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi',
              id: '2iDVt6mFbtbDEZG5ax0dTi',
              name: 'Tulus',
              type: 'artist',
              uri: 'spotify:artist:2iDVt6mFbtbDEZG5ax0dTi',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CD',
            'CG',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'ET',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IQ',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'LY',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TJ',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VE',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/0d5mFusjnb62TQWBft3zc6',
          },
          href: 'https://api.spotify.com/v1/albums/0d5mFusjnb62TQWBft3zc6',
          id: '0d5mFusjnb62TQWBft3zc6',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b2737c52c7f7d1da8625e4376795',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e027c52c7f7d1da8625e4376795',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d000048517c52c7f7d1da8625e4376795',
              width: 64,
            },
          ],
          name: 'Gajah',
          release_date: '2014-02-18',
          release_date_precision: 'day',
          total_tracks: 9,
          type: 'album',
          uri: 'spotify:album:0d5mFusjnb62TQWBft3zc6',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2iDVt6mFbtbDEZG5ax0dTi',
            },
            href: 'https://api.spotify.com/v1/artists/2iDVt6mFbtbDEZG5ax0dTi',
            id: '2iDVt6mFbtbDEZG5ax0dTi',
            name: 'Tulus',
            type: 'artist',
            uri: 'spotify:artist:2iDVt6mFbtbDEZG5ax0dTi',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'ET',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 219284,
        explicit: false,
        external_ids: {
          isrc: 'FR6V82272636',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/73DWDOjVUyJ8sAiAcySvgS',
        },
        href: 'https://api.spotify.com/v1/tracks/73DWDOjVUyJ8sAiAcySvgS',
        id: '73DWDOjVUyJ8sAiAcySvgS',
        is_local: false,
        name: 'Sepatu',
        popularity: 70,
        preview_url:
          'https://p.scdn.co/mp3-preview/499fa741165c884106e3a310eda58133432c0b0e?cid=b8b35b1f317e44f5a24f7617fe6eb34d',
        track_number: 3,
        type: 'track',
        uri: 'spotify:track:73DWDOjVUyJ8sAiAcySvgS',
      },
      played_at: '2023-01-16T11:35:18.943Z',
      context: null,
    },
    {
      track: {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/1jWIP5sLhDZttQeR0mPffn',
              },
              href: 'https://api.spotify.com/v1/artists/1jWIP5sLhDZttQeR0mPffn',
              id: '1jWIP5sLhDZttQeR0mPffn',
              name: 'Citra Scholastika',
              type: 'artist',
              uri: 'spotify:artist:1jWIP5sLhDZttQeR0mPffn',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CD',
            'CG',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'ET',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IQ',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'LY',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TJ',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VE',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/5xqW664Hhk6E6GUhKvG5nv',
          },
          href: 'https://api.spotify.com/v1/albums/5xqW664Hhk6E6GUhKvG5nv',
          id: '5xqW664Hhk6E6GUhKvG5nv',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273fd4c66dd8d9ae79889b0a45d',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02fd4c66dd8d9ae79889b0a45d',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851fd4c66dd8d9ae79889b0a45d',
              width: 64,
            },
          ],
          name: 'Pasti Bisa',
          release_date: '2014-10-14',
          release_date_precision: 'day',
          total_tracks: 12,
          type: 'album',
          uri: 'spotify:album:5xqW664Hhk6E6GUhKvG5nv',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1jWIP5sLhDZttQeR0mPffn',
            },
            href: 'https://api.spotify.com/v1/artists/1jWIP5sLhDZttQeR0mPffn',
            id: '1jWIP5sLhDZttQeR0mPffn',
            name: 'Citra Scholastika',
            type: 'artist',
            uri: 'spotify:artist:1jWIP5sLhDZttQeR0mPffn',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'ET',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 203173,
        explicit: false,
        external_ids: {
          isrc: 'IDA141303213',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/59hyYZHK01fZ3Xd64NMh3R',
        },
        href: 'https://api.spotify.com/v1/tracks/59hyYZHK01fZ3Xd64NMh3R',
        id: '59hyYZHK01fZ3Xd64NMh3R',
        is_local: false,
        name: 'Pasti Bisa',
        popularity: 57,
        preview_url:
          'https://p.scdn.co/mp3-preview/0fdb62bdfe2305940b8db95b80b0f9387db17eae?cid=b8b35b1f317e44f5a24f7617fe6eb34d',
        track_number: 10,
        type: 'track',
        uri: 'spotify:track:59hyYZHK01fZ3Xd64NMh3R',
      },
      played_at: '2023-01-16T11:33:14.569Z',
      context: null,
    },
    {
      track: {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/3D5DKmCiZ3VQRu68k87E3Q',
              },
              href: 'https://api.spotify.com/v1/artists/3D5DKmCiZ3VQRu68k87E3Q',
              id: '3D5DKmCiZ3VQRu68k87E3Q',
              name: 'Lala Karmela',
              type: 'artist',
              uri: 'spotify:artist:3D5DKmCiZ3VQRu68k87E3Q',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CD',
            'CG',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'ET',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IQ',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'LY',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TJ',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VE',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6XqNorK0XDn5kPMnqLuBxk',
          },
          href: 'https://api.spotify.com/v1/albums/6XqNorK0XDn5kPMnqLuBxk',
          id: '6XqNorK0XDn5kPMnqLuBxk',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273d462cb84c9899a5a132101a1',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02d462cb84c9899a5a132101a1',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851d462cb84c9899a5a132101a1',
              width: 64,
            },
          ],
          name: 'Kamu, Aku, Cinta',
          release_date: '2011-02-21',
          release_date_precision: 'day',
          total_tracks: 12,
          type: 'album',
          uri: 'spotify:album:6XqNorK0XDn5kPMnqLuBxk',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/00o36BiAS5VuyfvzNtd3Ig',
            },
            href: 'https://api.spotify.com/v1/artists/00o36BiAS5VuyfvzNtd3Ig',
            id: '00o36BiAS5VuyfvzNtd3Ig',
            name: 'Ello',
            type: 'artist',
            uri: 'spotify:artist:00o36BiAS5VuyfvzNtd3Ig',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0z62BK7Dlf4pui37XDARci',
            },
            href: 'https://api.spotify.com/v1/artists/0z62BK7Dlf4pui37XDARci',
            id: '0z62BK7Dlf4pui37XDARci',
            name: 'Barry',
            type: 'artist',
            uri: 'spotify:artist:0z62BK7Dlf4pui37XDARci',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5GlpZ7HnQxaNiHxPeE2bR3',
            },
            href: 'https://api.spotify.com/v1/artists/5GlpZ7HnQxaNiHxPeE2bR3',
            id: '5GlpZ7HnQxaNiHxPeE2bR3',
            name: 'Ipank',
            type: 'artist',
            uri: 'spotify:artist:5GlpZ7HnQxaNiHxPeE2bR3',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3D5DKmCiZ3VQRu68k87E3Q',
            },
            href: 'https://api.spotify.com/v1/artists/3D5DKmCiZ3VQRu68k87E3Q',
            id: '3D5DKmCiZ3VQRu68k87E3Q',
            name: 'Lala Karmela',
            type: 'artist',
            uri: 'spotify:artist:3D5DKmCiZ3VQRu68k87E3Q',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'ET',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 232746,
        explicit: false,
        external_ids: {
          isrc: 'IDAC50900194',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/6lZKJkfn0eVCXvbh1jsO8a',
        },
        href: 'https://api.spotify.com/v1/tracks/6lZKJkfn0eVCXvbh1jsO8a',
        id: '6lZKJkfn0eVCXvbh1jsO8a',
        is_local: false,
        name: 'Buka Semangat Baru',
        popularity: 49,
        preview_url:
          'https://p.scdn.co/mp3-preview/5a7972daabee88ee827d7411eaf4f5e268649fe0?cid=b8b35b1f317e44f5a24f7617fe6eb34d',
        track_number: 7,
        type: 'track',
        uri: 'spotify:track:6lZKJkfn0eVCXvbh1jsO8a',
      },
      played_at: '2023-01-16T11:29:50.588Z',
      context: null,
    },
    {
      track: {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/3D5DKmCiZ3VQRu68k87E3Q',
              },
              href: 'https://api.spotify.com/v1/artists/3D5DKmCiZ3VQRu68k87E3Q',
              id: '3D5DKmCiZ3VQRu68k87E3Q',
              name: 'Lala Karmela',
              type: 'artist',
              uri: 'spotify:artist:3D5DKmCiZ3VQRu68k87E3Q',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CD',
            'CG',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'ET',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IQ',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'LY',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TJ',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VE',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6XqNorK0XDn5kPMnqLuBxk',
          },
          href: 'https://api.spotify.com/v1/albums/6XqNorK0XDn5kPMnqLuBxk',
          id: '6XqNorK0XDn5kPMnqLuBxk',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273d462cb84c9899a5a132101a1',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02d462cb84c9899a5a132101a1',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851d462cb84c9899a5a132101a1',
              width: 64,
            },
          ],
          name: 'Kamu, Aku, Cinta',
          release_date: '2011-02-21',
          release_date_precision: 'day',
          total_tracks: 12,
          type: 'album',
          uri: 'spotify:album:6XqNorK0XDn5kPMnqLuBxk',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/00o36BiAS5VuyfvzNtd3Ig',
            },
            href: 'https://api.spotify.com/v1/artists/00o36BiAS5VuyfvzNtd3Ig',
            id: '00o36BiAS5VuyfvzNtd3Ig',
            name: 'Ello',
            type: 'artist',
            uri: 'spotify:artist:00o36BiAS5VuyfvzNtd3Ig',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0z62BK7Dlf4pui37XDARci',
            },
            href: 'https://api.spotify.com/v1/artists/0z62BK7Dlf4pui37XDARci',
            id: '0z62BK7Dlf4pui37XDARci',
            name: 'Barry',
            type: 'artist',
            uri: 'spotify:artist:0z62BK7Dlf4pui37XDARci',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5GlpZ7HnQxaNiHxPeE2bR3',
            },
            href: 'https://api.spotify.com/v1/artists/5GlpZ7HnQxaNiHxPeE2bR3',
            id: '5GlpZ7HnQxaNiHxPeE2bR3',
            name: 'Ipank',
            type: 'artist',
            uri: 'spotify:artist:5GlpZ7HnQxaNiHxPeE2bR3',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3D5DKmCiZ3VQRu68k87E3Q',
            },
            href: 'https://api.spotify.com/v1/artists/3D5DKmCiZ3VQRu68k87E3Q',
            id: '3D5DKmCiZ3VQRu68k87E3Q',
            name: 'Lala Karmela',
            type: 'artist',
            uri: 'spotify:artist:3D5DKmCiZ3VQRu68k87E3Q',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'ET',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 232746,
        explicit: false,
        external_ids: {
          isrc: 'IDAC50900194',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/6lZKJkfn0eVCXvbh1jsO8a',
        },
        href: 'https://api.spotify.com/v1/tracks/6lZKJkfn0eVCXvbh1jsO8a',
        id: '6lZKJkfn0eVCXvbh1jsO8a',
        is_local: false,
        name: 'Buka Semangat Baru',
        popularity: 49,
        preview_url:
          'https://p.scdn.co/mp3-preview/5a7972daabee88ee827d7411eaf4f5e268649fe0?cid=b8b35b1f317e44f5a24f7617fe6eb34d',
        track_number: 7,
        type: 'track',
        uri: 'spotify:track:6lZKJkfn0eVCXvbh1jsO8a',
      },
      played_at: '2023-01-11T10:07:00.034Z',
      context: null,
    },
    {
      track: {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/374NOHOFF57pYs9QOhuKJq',
              },
              href: 'https://api.spotify.com/v1/artists/374NOHOFF57pYs9QOhuKJq',
              id: '374NOHOFF57pYs9QOhuKJq',
              name: 'Sammy Simorangkir',
              type: 'artist',
              uri: 'spotify:artist:374NOHOFF57pYs9QOhuKJq',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CD',
            'CG',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'ET',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IQ',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'LY',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TJ',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VE',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/6oQ7gQBTguT0C6NvLgLhFw',
          },
          href: 'https://api.spotify.com/v1/albums/6oQ7gQBTguT0C6NvLgLhFw',
          id: '6oQ7gQBTguT0C6NvLgLhFw',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273bbc5ad8c441fe398b7e055c5',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02bbc5ad8c441fe398b7e055c5',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851bbc5ad8c441fe398b7e055c5',
              width: 64,
            },
          ],
          name: 'Aku Kembali (Repackage)',
          release_date: '2013-09-02',
          release_date_precision: 'day',
          total_tracks: 12,
          type: 'album',
          uri: 'spotify:album:6oQ7gQBTguT0C6NvLgLhFw',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/374NOHOFF57pYs9QOhuKJq',
            },
            href: 'https://api.spotify.com/v1/artists/374NOHOFF57pYs9QOhuKJq',
            id: '374NOHOFF57pYs9QOhuKJq',
            name: 'Sammy Simorangkir',
            type: 'artist',
            uri: 'spotify:artist:374NOHOFF57pYs9QOhuKJq',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CD',
          'CG',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'ET',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IQ',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'LY',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TJ',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VE',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 296693,
        explicit: false,
        external_ids: {
          isrc: 'FR6V82266031',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/3rTAo5BNwhtEtlOpRemePc',
        },
        href: 'https://api.spotify.com/v1/tracks/3rTAo5BNwhtEtlOpRemePc',
        id: '3rTAo5BNwhtEtlOpRemePc',
        is_local: false,
        name: 'Sudahi Semua Ini',
        popularity: 26,
        preview_url:
          'https://p.scdn.co/mp3-preview/eab672e1652e2c0aea2a4e4ee2597f953d9c2bc2?cid=b8b35b1f317e44f5a24f7617fe6eb34d',
        track_number: 8,
        type: 'track',
        uri: 'spotify:track:3rTAo5BNwhtEtlOpRemePc',
      },
      played_at: '2023-01-11T00:10:26.922Z',
      context: {
        external_urls: {
          spotify: 'https://open.spotify.com/playlist/37i9dQZF1E350YpTbotW9I',
        },
        href: 'https://api.spotify.com/v1/playlists/37i9dQZF1E350YpTbotW9I',
        type: 'playlist',
        uri: 'spotify:playlist:37i9dQZF1E350YpTbotW9I',
      },
    },
  ],
  next: 'https://api.spotify.com/v1/me/player/recently-played?before=1672886668075',
  cursors: {
    after: '1673868918943',
    before: '1672886668075',
  },
  limit: 20,
  href: 'https://api.spotify.com/v1/me/player/recently-played',
};

const displayTrackName = (trackName: string) => {
  const MAX_TRACK_NAME_LENGTH = 15;

  if (trackName.length <= MAX_TRACK_NAME_LENGTH) {
    return trackName;
  }

  return `${trackName.slice(0, MAX_TRACK_NAME_LENGTH)}...`;
};

const displayArtistName = (artistName: string) => {
  const MAX_ARTIST_NAME_LENGTH = 23;

  if (artistName.length <= MAX_ARTIST_NAME_LENGTH) {
    return artistName;
  }

  return `${artistName.slice(0, MAX_ARTIST_NAME_LENGTH)}...`;
};

export function RecentlyPlayed() {
  return (
    <section className="space-y-4">
      <h2 className="text-2xl font-bold text-gray-200">Recently Played</h2>
      <RecentlyPlayedList
        tracks={mockItems.items.map((item) => ({
          songName: displayTrackName(item.track.name),
          albumImg: item.track.album.images[0].url,
          albumName: item.track.album.name,
          artistName: displayArtistName(item.track.artists[0].name),
        }))}
      />
    </section>
  );
}

export default RecentlyPlayed;
