name: test-auth-utils

on:
  push:
    branches: [main]
    paths:
      - 'libs/auth-utils/**'
      - '.github/workflows/auth-utils-test.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
  test:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: run unit test
        run: yarn test auth-utils --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: '**/coverage/libs/auth-utils/coverage-final.json'
          flag: auth-utils
